---
ID: "fe4bf23d-9fc0-4469-b2a5-6bc71893a468"
Parent: "34cc6f8a-9980-45a1-9a07-ebe18748a57f"
Template: "34cc6f8a-9980-45a1-9a07-ebe18748a57f"
Path: /sitecore/templates/Project/officecore/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{34CC6F8A-9980-45A1-9A07-EBE18748A57F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{DE1B958B-4E8F-491D-AB4C-A654B982A97B}"
              p:after="p[@uid='{F1E8C0CE-B80C-502D-B7B6-A53A17BEAC12}']"
              s:ds="{D67C4E4D-02A6-432C-A4C4-16C64FBB93E4}"
              s:id="{AE917C70-594A-44A5-89FC-FB36F2FD1582}"
              s:par=""
              s:ph="jss-header"
              s:ccb="Clear on publish" />
            <r
              uid="{5E4D1EFE-B9DB-4DA2-A6A7-2A9F6F58BEE3}"
              p:after="r[@uid='{DE1B958B-4E8F-491D-AB4C-A654B982A97B}']"
              s:id="{F165F480-042A-4349-BC07-029630AEFBFC}"
              s:ph="jss-main" />
            <r
              uid="{FB89CABF-7AE0-4876-8B93-674AB9956AEB}"
              p:after="*[1=2]"
              s:ds="{0BDE3DA8-4C10-4B99-9FD7-AA5EF1D954F0}"
              s:id="{36411F42-D448-47C6-87DC-BD57B48CF376}"
              s:par=""
              s:ph="jss-footer"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "1124de2d-ddc6-5a74-a80f-2f4183715a94"
      Hint: pageTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220324T152351Z
    - ID: "4fa7a453-e6de-4940-8dd6-7660f0aa4073"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "671a4940-b938-4c46-a338-522b2de10e7f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220526T160941Z
