---
ID: "e1eb2e3a-dd98-4ecd-a878-e3adda3f1af6"
Parent: "82204080-c41f-42fe-b88e-01c1c1a6befa"
Template: "82204080-c41f-42fe-b88e-01c1c1a6befa"
Path: /sitecore/templates/Project/officecore/Product Section/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{8FB1D232-8ECD-4201-A51F-873FF629CB93}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{DE1B958B-4E8F-491D-AB4C-A654B982A97B}"
              p:after="p[@uid='{F1E8C0CE-B80C-502D-B7B6-A53A17BEAC12}']"
              s:ds="{D67C4E4D-02A6-432C-A4C4-16C64FBB93E4}"
              s:id="{AE917C70-594A-44A5-89FC-FB36F2FD1582}"
              s:par=""
              s:ph="jss-header"
              s:ccb="Clear on publish" />
            <r
              uid="{E1CD8C8B-E9B0-4ED8-B980-FD6B2EE14AF1}"
              p:after="r[@uid='{DE1B958B-4E8F-491D-AB4C-A654B982A97B}']"
              s:id="{F165F480-042A-4349-BC07-029630AEFBFC}"
              s:ph="jss-main" />
            <r
              uid="{289B3F6F-A87B-4A20-8BBA-D8EBE87230A1}"
              p:after="r[@uid='{E1CD8C8B-E9B0-4ED8-B980-FD6B2EE14AF1}']"
              s:id="{CEE37B69-D922-493D-B695-A123842A3BE5}"
              s:ph="jss-main" />
            <r
              uid="{FB89CABF-7AE0-4876-8B93-674AB9956AEB}"
              p:after="*[1=2]"
              s:ds="{0BDE3DA8-4C10-4B99-9FD7-AA5EF1D954F0}"
              s:id="{36411F42-D448-47C6-87DC-BD57B48CF376}"
              s:par=""
              s:ph="jss-footer"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220329T143736Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "75e4336d-54da-4ea0-bd50-9135b0285deb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220530T144943Z
